# Generated by Django 4.2.20 on 2025-03-22 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodik', models.CharField(max_length=100, verbose_name='Periodik Maintenance')),
                ('tanggal_maintenance', models.DateField(auto_now_add=True, verbose_name='Tanggal Maintenance')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('pelaksana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pelaksana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Perawatan Motor',
                'verbose_name_plural': 'Data Perawatan Motor',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='Tag No')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor Name')),
                ('output', models.FloatField(blank=True, help_text='Daya dalam KW', null=True, verbose_name='Output')),
                ('voltage', models.FloatField(blank=True, help_text='Tegangan dalam Volt', null=True, verbose_name='Voltage')),
                ('starter_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Starter Type')),
                ('set_ol', models.FloatField(blank=True, null=True, verbose_name='SET OL')),
                ('input', models.FloatField(blank=True, help_text='Arus dalam Ampere', null=True, verbose_name='Input')),
                ('speed', models.FloatField(blank=True, help_text='RPM', null=True, verbose_name='Speed')),
                ('frek', models.FloatField(blank=True, null=True, verbose_name='FREK/WEN/CY/HZ')),
                ('frame', models.CharField(blank=True, max_length=50, null=True, verbose_name='Frame')),
                ('foundation_type', models.CharField(blank=True, help_text='Rigid atau Flexible', max_length=50, null=True, verbose_name='Fondation Type')),
                ('class_type', models.CharField(blank=True, help_text='Kelas 2 atau 3', max_length=50, null=True, verbose_name='Class Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Daftar Motor',
            },
        ),
        migrations.CreateModel(
            name='Vibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tanggal dibuat')),
                ('vib_rigid_de', models.FloatField(blank=True, help_text='Maksimal 4,5 mm/s', null=True, verbose_name='Rigid D.E')),
                ('vib_rigid_nde', models.FloatField(blank=True, help_text='Maksimal 4,5 mm/s', null=True, verbose_name='Rigid N.D.E')),
                ('vib_flexible_de', models.FloatField(blank=True, help_text='Maksimal 7,1 mm/s', null=True, verbose_name='Flexible D.E')),
                ('vib_flexible_nde', models.FloatField(blank=True, help_text='Maksimal 7,1 mm/s', null=True, verbose_name='Flexible N.D.E')),
                ('vib_class_2_de', models.FloatField(blank=True, help_text='Maksimal 4gE', null=True, verbose_name='Class 2 D.E')),
                ('vib_class_2_nde', models.FloatField(blank=True, help_text='Maksimal 4gE', null=True, verbose_name='Class 2 N.D.E')),
                ('vib_class_3_de', models.FloatField(blank=True, help_text='Maksimal 10gE', null=True, verbose_name='Class 3 D.E')),
                ('vib_class_3_nde', models.FloatField(blank=True, help_text='Maksimal 10gE', null=True, verbose_name='Class 3 N.D.E')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.maintenance', verbose_name='Perawatan')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.motor', verbose_name='Motor')),
            ],
            options={
                'verbose_name': 'Getaran Motor',
                'verbose_name_plural': 'Data Getaran Motor',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tanggal dibuat')),
                ('load_current_r', models.FloatField(blank=True, help_text='Arus dalam Ampere', null=True, verbose_name='Load Current R')),
                ('load_current_s', models.FloatField(blank=True, help_text='Arus dalam Ampere', null=True, verbose_name='Load Current S')),
                ('load_current_t', models.FloatField(blank=True, help_text='Arus dalam Ampere', null=True, verbose_name='Load Current T')),
                ('bearing_temp_de', models.FloatField(blank=True, help_text='Maksimal 80°', null=True, verbose_name='Bearing D.E')),
                ('bearing_temp_nde', models.FloatField(blank=True, help_text='Maksimal 80°', null=True, verbose_name='Bearing N.D.E')),
                ('coil_temp', models.FloatField(blank=True, help_text='Maksimal 80°', null=True, verbose_name='Coil Temp')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.maintenance', verbose_name='Perawatan')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.motor', verbose_name='Motor')),
            ],
            options={
                'verbose_name': 'Pengukuran Motor',
                'verbose_name_plural': 'Data Pengukuran Motor',
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.motor', verbose_name='Motor yang Dimaintenance'),
        ),
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
